_wandb:
    value:
        cli_version: 0.23.1
        e:
            3up8dmv4crncid3u1if1bczfbymzv05q:
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1022746423296"
                        used: "540362878976"
                email: s181487@dtu.dk
                executable: C:\Users\Jacob pc\vscode_projects\mlops2\.venv\Scripts\python.exe
                git:
                    commit: 10a54f48a679d89729ca386e64685e9eb559342b
                    remote: https://github.com/JBorregaardd/mlops2.git
                gpu: NVIDIA GeForce RTX 2070 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2070 SUPER
                      uuid: GPU-6cd2715a-d2f3-d6e4-a077-9299fa711768
                host: DESKTOP-QKDN8RQ
                memory:
                    total: "17094889472"
                os: Windows-11-10.0.26200-SP0
                program: -m mlopscookie.train
                python: CPython 3.13.11
                root: C:\Users\Jacob pc\vscode_projects\mlops2
                startedAt: "2026-01-08T10:24:02.186887Z"
                writerId: 3up8dmv4crncid3u1if1bczfbymzv05q
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 50
            "2":
                - 1
                - 50
            "3":
                - 16
            "4": 3.13.11
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 5
lr:
    value: 0.001
